### ISSUE TITLE
Crash on trigger

### ISSUE THREAD

**Issue by dbankier** [mopinion/mopinion-sdk-android-web#1]
Here is the error:

```
01-27 10:15:40.914 30119 30119 D AndroidRuntime: Shutting down VM
01-27 10:15:40.914 30119 30119 E AndroidRuntime: FATAL EXCEPTION: main
01-27 10:15:40.914 30119 30119 E AndroidRuntime: Process: xx.xxxx.xxxx PID: 30119
01-27 10:15:40.914 30119 30119 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{xx.xxxx.xxxx/com.mopinion.mopinionsdkweb.MopinionWeb}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-27 10:15:40.914 30119 30119 E AndroidRuntime: Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:201)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:129)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at com.mopinion.mopinionsdkweb.MopinionWeb.openWebView(MopinionWeb.java:205)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at com.mopinion.mopinionsdkweb.MopinionWeb.onCreate(MopinionWeb.java:66)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7825)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7814)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
01-27 10:15:40.914 30119 30119 E AndroidRuntime:        ... 11 more
```

**Comment by Piethot** [comment]
Hi David, thanks for reporting this issue. We will investigate and inform you of the progress we are making.

**Comment by saenic** [comment]
I had the same crash. You guys are not providing a theme, therefore we have to set 
`        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>`
in the application theme.

So please provide a theme for your `MopinionWeb` Activity

**Comment by GustaafL** [comment]
Hi All,

A new version of the SDK 0.1.7 was released to deal with this issue. Thank you for reporting this issue.
